dist: trusty
language: elixir
elixir: 1.5.2
otp_release: 20.1
addons:
  postgresql: 9.6
env:
  global:
    - MIX_ENV=test
    - HEXPM_PATH=..
    - HEXWEB_PATH=..
  matrix:
    - HEX_VERSION=wm-hex-tar-elixir
before_script:
  - mix ecto.create
  - git clone https://github.com/hexpm/hex hex -b ${HEX_VERSION} --depth 1
script:
  - cd hex; mix deps.get && mix test --include integration && mix install
  - mix test --include integration
  - mix run priv/repo/seeds.exs
notifications:
  recipients:
  - eric.meadows.jonsson@gmail.com
  slack:
    secure: D21dsphy22i/G+yujf1V4f2x9pnbmTr2BkZv3nifXggTXY+ObItQ2MM/j9AoObdusbV63eSpvBZTIfX/oe7DQjN8hHBc/aILMZMLq7gKpOCTLtWIVvS9vNkyLa33EWwF/CsMiYQh377vye8a7cvORlkPmf+rNV//E9mbpuIWzBI=
